name: linux_build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-g:
    name: Build GCC
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++ cmake
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build

  
  build-clang:
    name: Build Clang
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y clang cmake
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build
